### ISSUE TITLE
it's not possible to re-use the existing default github.com endpoint

### ISSUE THREAD

**Issue by bavarianbidi** [mercedes-benz/garm-operator#187]
### What is the feature you would like to have?

It should be possible to use the existing default github.com GitHubEndpoint without the need of doing some additional hacks.

### Anything else you would like to add?

garm shipps with a  github endpoint configuration per default.
It's not possible to change this github configuration via CLI/API due to [this condition in garm](https://github.com/cloudbase/garm/blob/main/database/sql/github.go#L166C1-L169C3).

By using the operator, it's currently needed to create a copy of the github Endpoint definition to make use of the github.com endpoint.

```yaml
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: GitHubEndpoint
metadata:
  name: github
spec:
  description: "github.com"
  apiBaseUrl: "https://api.github.com"
  uploadBaseUrl: "https://uploads.github.com"
  baseUrl: "https://github.com"
```
